import { CircleAlert, ShieldCheck } from "lucide-react";
import { type ReactElement, useState } from "react";
import type { Project } from "../data/enforcerAppData";

export type SecurityProfilePayload = { sourcePath: string; profileName: string; requiredTestCategories: string[]; invariants: string[]; rules: Array<{ ruleId: string; tier: string; backed: boolean }>; activated: boolean; projectActivation: string; caveat: string };
type AssuranceTab = "profile" | "tests" | "invariants" | "rules";

export function AssuranceWorkspace({ project, profile, loading, error, onActivate }: { project: Project; profile?: SecurityProfilePayload | undefined; loading: boolean; error: string; onActivate: (request: { sourceSpec: string; owner: string; reason: string }) => Promise<void> }): ReactElement {
  const [sourceSpec, setSourceSpec] = useState(""); const [owner, setOwner] = useState(""); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState("");
  const [tab, setTab] = useState<AssuranceTab>("profile");
  return <section className="main-surface assurance-workspace">
    <div className="panel-head"><span><strong>Assurance</strong><small>Security and money-critical posture for {project.name}. Profile availability is not project activation.</small></span><ShieldCheck size={20} /></div>
    <div className="assurance-content">
      {loading && <div className="run-status">Reading Rust-owned security profile.</div>}
      {error && <div className="index-error">{error}</div>}
      {profile && <><div className="assurance-tabs" role="tablist" aria-label="Assurance sections"><button role="tab" aria-selected={tab === "profile"} className={tab === "profile" ? "active" : ""} onClick={() => setTab("profile")}>Profile</button><button role="tab" aria-selected={tab === "tests"} className={tab === "tests" ? "active" : ""} onClick={() => setTab("tests")}>Test categories</button><button role="tab" aria-selected={tab === "invariants"} className={tab === "invariants" ? "active" : ""} onClick={() => setTab("invariants")}>Invariants</button><button role="tab" aria-selected={tab === "rules"} className={tab === "rules" ? "active" : ""} onClick={() => setTab("rules")}>Rules</button></div>
      {tab === "profile" && <><div className="assurance-caveat"><CircleAlert size={17} /><span>{profile.caveat}</span></div><div className="settings-root-row"><span>Profile source</span><code>{profile.sourcePath}</code></div><div className="assurance-summary"><span><strong>{profile.rules.filter((rule) => rule.backed).length}</strong><small>backed rules</small></span><span><strong>{profile.requiredTestCategories.length}</strong><small>required test categories</small></span><span><strong>{profile.invariants.length}</strong><small>declared invariants</small></span></div><div className="assurance-activation"><strong>Selected project</strong><span>{profile.projectActivation}</span></div>{!profile.activated && <div className="assurance-form"><label>Source specification<input value={sourceSpec} onChange={(event) => setSourceSpec(event.target.value)} placeholder="path or policy source" /></label><label>Owner<input value={owner} onChange={(event) => setOwner(event.target.value)} placeholder="team or person" /></label><label>Reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="why this profile applies" /></label>{saveError && <div className="index-error">{saveError}</div>}<button className="primary-action" disabled={!sourceSpec.trim() || !owner.trim() || !reason.trim() || saving} onClick={() => { setSaving(true); setSaveError(""); void onActivate({ sourceSpec: sourceSpec.trim(), owner: owner.trim(), reason: reason.trim() }).catch((activationError) => { setSaveError(String(activationError)); setSaving(false); }); }}>{saving ? "Activating" : "Activate profile"}</button></div>}</>}
      {tab === "tests" && <div className="assurance-list"><div className="detail-heading"><ShieldCheck size={17} /><strong>Required test categories</strong></div>{profile.requiredTestCategories.map((item) => <code key={item}>{item}</code>)}</div>}
      {tab === "invariants" && <div className="assurance-list"><div className="detail-heading"><ShieldCheck size={17} /><strong>Declared invariants</strong></div>{profile.invariants.map((item) => <code key={item}>{item}</code>)}</div>}
      {tab === "rules" && <div className="assurance-rules"><div className="detail-heading"><ShieldCheck size={17} /><strong>Mechanized profile rules</strong></div>{profile.rules.map((rule) => <div key={rule.ruleId}><code>{rule.ruleId}</code><span>{rule.tier}</span><em className={rule.backed ? "connected" : "attention"}>{rule.backed ? "backed" : "unbacked"}</em></div>)}</div>}</>}
    </div>
  </section>;
}
