import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SCRIPT = path.join(ROOT, 'scripts', 'rust-rules.mjs');

function makeProject(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ocentra-enforcer-multilang-'));
  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content.trimStart(), 'utf8');
  }
  return dir;
}

function run(project, args) {
  return spawnSync(process.execPath, [SCRIPT, ...args, '--root', project], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
}

test('TypeScript and common scanners catch source, test, generated, and secret policy violations', () => {
  const project = makeProject({
    'src/index.ts': `
import { z } from "zod";
export { Thing } from "./thing";
type UserId = string;
type ManualBrand = string & { readonly __brand: "ManualBrand" };
// @ts-ignore
const apiKey = "sk_test_1234567890abcdef";
`,
    'src/generated.ts': `
// @generated by a tool
export const generatedValue = 1;
`,
    'tests/example.test.ts': `
vi.mock("bad");
test.skip("bad", () => {
  expect(true).toBe(true);
});
`,
  });
  const result = run(project, ['scan', '--json', '--languages', 'typescript,common', '--files', 'src', 'tests']);
  assert.notEqual(result.status, 0, result.stdout || result.stderr);
  const report = JSON.parse(result.stdout);
  assert.deepEqual(report.languages, ['typescript', 'common']);
  const ids = report.violations.map((violation) => violation.ruleId).sort();
  assert.equal(ids.includes('TS-1.1'), true);
  assert.equal(ids.includes('TS-1.2'), true);
  assert.equal(ids.includes('TS-1.3'), true);
  assert.equal(ids.includes('TS-2.1'), true);
  assert.equal(ids.includes('TS-3.1'), true);
  assert.equal(ids.includes('TEST-1.1'), true);
  assert.equal(ids.includes('SEC-1.1'), true);
  assert.equal(ids.includes('GEN-1.1'), true);
});

test('common scanner catches sensitive paths, generated output paths, and unguarded platform-specific commands', () => {
  const project = makeProject({
    '.env': 'OPENAI_API_KEY=local-only\n',
    'test-results/report.json': '{"ok":true}\n',
    'scripts/run.mjs': `
import { spawnSync } from "node:child_process";
spawnSync("cmd", ["/c", "npm", "test"]);
`,
  });
  const result = run(project, ['scan', '--json', '--languages', 'common', '--files', '.env', 'test-results', 'scripts']);
  assert.notEqual(result.status, 0, result.stdout || result.stderr);
  const report = JSON.parse(result.stdout);
  const ids = report.violations.map((violation) => violation.ruleId).sort();
  assert.equal(ids.includes('SEC-1.2'), true);
  assert.equal(ids.includes('GEN-1.2'), true);
  assert.equal(ids.includes('PORT-1.1'), true);
});

test('Python scanner catches lint/type suppressions and skipped tests', () => {
  const project = makeProject({
    'src/app.py': `
value = dynamic()  # type: ignore
other = 1  # noqa
`,
    'tests/test_app.py': `
import pytest

@pytest.mark.skip("not today")
def test_app():
    assert True
`,
  });
  const result = run(project, ['scan', '--json', '--languages', 'python,common', '--files', 'src', 'tests']);
  assert.notEqual(result.status, 0, result.stdout || result.stderr);
  const report = JSON.parse(result.stdout);
  const ids = report.violations.map((violation) => violation.ruleId).sort();
  assert.equal(ids.includes('PY-1.1'), true);
  assert.equal(ids.includes('PY-1.2'), true);
  assert.equal(ids.includes('PY-2.1'), true);
});

test('documentation advisory warnings do not fail by default', () => {
  const project = makeProject({
    'src/api.ts': `
export function makeThing() {
  return 1;
}
`,
  });
  const result = run(project, ['scan', '--json', '--languages', 'typescript,common', '--files', 'src']);
  assert.equal(result.status, 0, result.stdout || result.stderr);
  const report = JSON.parse(result.stdout);
  assert.equal(report.ok, true);
  assert.deepEqual(report.violations, []);
  assert.equal(report.warnings.some((finding) => finding.ruleId === 'DOC-1.1' && finding.severity === 'warning'), true);
});

test('profile can promote advisory documentation warnings to hard failures', () => {
  const project = makeProject({
    'ocentra-enforcer.config.json': JSON.stringify({
      rules: {
        'DOC-1.1': { severity: 'error' },
      },
    }),
    'src/api.ts': `
export function makeThing() {
  return 1;
}
`,
  });
  const result = run(project, ['scan', '--json', '--languages', 'typescript,common', '--files', 'src']);
  assert.notEqual(result.status, 0, result.stdout || result.stderr);
  const report = JSON.parse(result.stdout);
  assert.equal(report.violations.some((finding) => finding.ruleId === 'DOC-1.1' && finding.severity === 'error'), true);
});

test('profile can downgrade a normally hard rule to warning', () => {
  const project = makeProject({
    'ocentra-enforcer.config.json': JSON.stringify({
      rules: {
        'TS-2.1': { severity: 'warning' },
        'DOC-1.1': { enabled: false },
      },
    }),
    'src/api.ts': `
// @ts-ignore
const value = dynamicValue;
`,
  });
  const result = run(project, ['scan', '--json', '--languages', 'typescript,common', '--files', 'src']);
  assert.equal(result.status, 0, result.stdout || result.stderr);
  const report = JSON.parse(result.stdout);
  assert.deepEqual(report.violations, []);
  assert.equal(report.warnings.some((finding) => finding.ruleId === 'TS-2.1' && finding.severity === 'warning'), true);
});

test('route command returns TypeScript, Python, and common docs without loading unknown files', () => {
  const project = makeProject({ 'README.md': '# fixture\n' });
  const tsRoute = run(project, ['route', '--json', '--files', 'src/index.ts', 'tests/example.test.ts']);
  assert.equal(tsRoute.status, 0, tsRoute.stdout || tsRoute.stderr);
  const tsReport = JSON.parse(tsRoute.stdout);
  assert.equal(tsReport.docs.includes('rules/typescript/source.md#covered-rules'), true);
  assert.equal(tsReport.docs.includes('rules/typescript/tests.md#covered-rules'), true);
  assert.equal(tsReport.docs.includes('rules/common/security.md#covered-rules'), true);

  const pyRoute = run(project, ['route', '--json', '--files', 'tests/test_app.py']);
  const pyReport = JSON.parse(pyRoute.stdout);
  assert.equal(pyReport.docs.includes('rules/python/source.md#covered-rules'), true);
  assert.equal(pyReport.docs.includes('rules/python/tests.md#covered-rules'), true);

  const unknownRoute = run(project, ['route', '--json', '--files', 'README.md']);
  const unknownReport = JSON.parse(unknownRoute.stdout);
  assert.deepEqual(unknownReport.docs, []);
  assert.deepEqual(unknownReport.rules, []);
});
