//! BOUNDARY-INVARIANT: this boundary module validates raw wire values and converts only through typed domain contracts.
//! Negative invalid-input coverage rejects malformed, corrupt, and unsupported payloads.
use super::{LanguageFamily, LanguageSpec};
use enforcer_domain::scan_types::{
    LiteralBasenameSet, LiteralExtensionSet, LiteralLanguageName, LiteralStringSyntaxProfile,
};
use std::ffi::OsStr;
use std::path::Path;

macro_rules! spec {
    ($id:expr, $family:expr, $extensions:expr, $basenames:expr, $single:expr, $backtick:expr, $triple:expr $(,)?) => {
        LanguageSpec {
            id: LiteralLanguageName::from_static($id),
            family: $family,
            extensions: LiteralExtensionSet::from_static($extensions),
            basenames: LiteralBasenameSet::from_static($basenames),
            syntax: LiteralStringSyntaxProfile::from_bits(
                (u8::from($single) * LiteralStringSyntaxProfile::SINGLE_QUOTE)
                    | (u8::from($backtick) * LiteralStringSyntaxProfile::BACKTICK)
                    | (u8::from($triple) * LiteralStringSyntaxProfile::TRIPLE_DOUBLE),
            ),
        }
    };
}

/// Return the curated language definitions recognized by literal discovery.
pub fn language_registry() -> Vec<LanguageSpec> {
    vec![
        spec!(
            "rust",
            LanguageFamily::Rust,
            &["rs"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "typescript",
            LanguageFamily::TypeScript,
            &["ts", "tsx", "mts", "cts"],
            &[],
            true,
            true,
            false,
        ),
        spec!(
            "javascript",
            LanguageFamily::TypeScript,
            &["js", "jsx", "mjs", "cjs"],
            &[],
            true,
            true,
            false,
        ),
        spec!(
            "python",
            LanguageFamily::Python,
            &["py", "pyw"],
            &[],
            true,
            false,
            true,
        ),
        spec!(
            "c",
            LanguageFamily::CLike,
            &["c", "h"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "cpp",
            LanguageFamily::CLike,
            &["cc", "cpp", "cxx", "hpp", "hxx", "hh"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "csharp",
            LanguageFamily::CLike,
            &["cs"],
            &[],
            true,
            false,
            true,
        ),
        spec!(
            "objective-c",
            LanguageFamily::CLike,
            &["m", "mm"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "zig",
            LanguageFamily::CLike,
            &["zig"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "go",
            LanguageFamily::CLike,
            &["go"],
            &[],
            false,
            true,
            false,
        ),
        spec!("d", LanguageFamily::CLike, &["d"], &[], false, true, false),
        spec!("v", LanguageFamily::CLike, &["v"], &[], false, true, false),
        spec!(
            "nim",
            LanguageFamily::HashComment,
            &["nim"],
            &[],
            true,
            true,
            true,
        ),
        spec!(
            "java",
            LanguageFamily::CLike,
            &["java"],
            &[],
            false,
            false,
            true,
        ),
        spec!(
            "kotlin",
            LanguageFamily::CLike,
            &["kt", "kts"],
            &[],
            true,
            false,
            true,
        ),
        spec!(
            "scala",
            LanguageFamily::CLike,
            &["scala", "sc"],
            &[],
            true,
            false,
            true,
        ),
        spec!(
            "groovy",
            LanguageFamily::CLike,
            &["groovy", "gradle"],
            &[],
            true,
            true,
            true,
        ),
        spec!(
            "swift",
            LanguageFamily::CLike,
            &["swift"],
            &[],
            false,
            false,
            true,
        ),
        spec!(
            "dart",
            LanguageFamily::CLike,
            &["dart"],
            &[],
            true,
            true,
            true,
        ),
        spec!(
            "php",
            LanguageFamily::CLike,
            &["php", "phtml"],
            &[],
            true,
            true,
            false,
        ),
        spec!(
            "ruby",
            LanguageFamily::HashComment,
            &["rb"],
            &[],
            true,
            true,
            true,
        ),
        spec!(
            "perl",
            LanguageFamily::HashComment,
            &["pl", "pm"],
            &[],
            true,
            true,
            false,
        ),
        spec!(
            "lua",
            LanguageFamily::HashComment,
            &["lua"],
            &[],
            true,
            false,
            true,
        ),
        spec!(
            "r",
            LanguageFamily::HashComment,
            &["r", "R"],
            &[],
            true,
            true,
            false,
        ),
        spec!(
            "julia",
            LanguageFamily::HashComment,
            &["jl"],
            &[],
            true,
            false,
            true,
        ),
        spec!(
            "shell",
            LanguageFamily::Shell,
            &["sh", "bash", "zsh", "fish"],
            &[],
            true,
            true,
            false,
        ),
        spec!(
            "powershell",
            LanguageFamily::Shell,
            &["ps1", "psm1", "psd1"],
            &[],
            true,
            true,
            true,
        ),
        spec!(
            "batch",
            LanguageFamily::Shell,
            &["bat", "cmd"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "make",
            LanguageFamily::Shell,
            &["mk"],
            &["Makefile", "makefile"],
            true,
            true,
            false,
        ),
        spec!(
            "dockerfile",
            LanguageFamily::Shell,
            &[],
            &["Dockerfile", "Containerfile"],
            true,
            true,
            false,
        ),
        spec!(
            "haskell",
            LanguageFamily::CLike,
            &["hs", "lhs"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "ocaml",
            LanguageFamily::CLike,
            &["ml", "mli"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "fsharp",
            LanguageFamily::CLike,
            &["fs", "fsx", "fsi"],
            &[],
            true,
            true,
            true,
        ),
        spec!(
            "elm",
            LanguageFamily::CLike,
            &["elm"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "purescript",
            LanguageFamily::CLike,
            &["purs"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "elixir",
            LanguageFamily::HashComment,
            &["ex", "exs"],
            &[],
            true,
            true,
            true,
        ),
        spec!(
            "erlang",
            LanguageFamily::CLike,
            &["erl", "hrl"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "clojure",
            LanguageFamily::Lisp,
            &["clj", "cljs", "cljc", "edn"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "lisp",
            LanguageFamily::Lisp,
            &["lisp", "lsp", "scm", "rkt", "el"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "sql",
            LanguageFamily::Sql,
            &["sql", "psql", "mysql", "sqlite"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "graphql",
            LanguageFamily::CommonText,
            &["graphql", "gql"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "terraform",
            LanguageFamily::CommonText,
            &["tf", "tfvars", "hcl"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "nix",
            LanguageFamily::CLike,
            &["nix"],
            &[],
            true,
            false,
            true,
        ),
        spec!(
            "starlark",
            LanguageFamily::HashComment,
            &["bzl", "star"],
            &[],
            true,
            false,
            true,
        ),
        spec!(
            "protobuf",
            LanguageFamily::CLike,
            &["proto"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "thrift",
            LanguageFamily::CLike,
            &["thrift"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "solidity",
            LanguageFamily::CLike,
            &["sol"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "move",
            LanguageFamily::CLike,
            &["move"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "apex",
            LanguageFamily::CLike,
            &["cls", "trigger"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "qml",
            LanguageFamily::CLike,
            &["qml"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "cuda",
            LanguageFamily::CLike,
            &["cu", "cuh"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "shader",
            LanguageFamily::CLike,
            &["glsl", "vert", "frag", "geom", "tesc", "tese", "hlsl", "wgsl",],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "raku",
            LanguageFamily::HashComment,
            &["raku", "rakumod", "p6", "pm6"],
            &[],
            true,
            true,
            true,
        ),
        spec!(
            "reason",
            LanguageFamily::CLike,
            &["re", "rei"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "rescript",
            LanguageFamily::CLike,
            &["res", "resi"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "sml",
            LanguageFamily::CLike,
            &["sml", "sig"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "avro",
            LanguageFamily::CommonText,
            &["avsc"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "html",
            LanguageFamily::Markup,
            &["html", "htm", "vue", "svelte", "astro"],
            &[],
            true,
            true,
            false,
        ),
        spec!(
            "css",
            LanguageFamily::CommonText,
            &["css", "scss", "sass", "less"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "json",
            LanguageFamily::CommonText,
            &["json", "jsonc"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "yaml",
            LanguageFamily::CommonText,
            &["yaml", "yml"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "toml",
            LanguageFamily::CommonText,
            &["toml"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "env",
            LanguageFamily::CommonText,
            &["env"],
            &[".env", ".env.local", ".env.example"],
            true,
            false,
            false,
        ),
        spec!(
            "markdown",
            LanguageFamily::CommonText,
            &["md", "mdx", "txt"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "xml",
            LanguageFamily::CommonText,
            &["xml"],
            &[],
            true,
            false,
            false,
        ),
        spec!(
            "csv",
            LanguageFamily::CommonText,
            &["csv"],
            &[],
            false,
            false,
            false,
        ),
        spec!(
            "coldfusion",
            LanguageFamily::Markup,
            &["cfc", "cfm"],
            &[],
            true,
            false,
            false,
        ),
    ]
}

pub(crate) fn detect_language(path: &Path, include_unknown: bool) -> Option<LanguageSpec> {
    let registry = language_registry();
    let basename = path.file_name().and_then(OsStr::to_str).unwrap_or("");
    for spec in &registry {
        if spec.basenames.as_slice().contains(&basename) {
            return Some(*spec);
        }
    }
    let ext = path.extension().and_then(OsStr::to_str).unwrap_or("");
    for spec in &registry {
        if spec
            .extensions
            .as_slice()
            .iter()
            .any(|candidate| candidate.eq_ignore_ascii_case(ext))
        {
            return Some(*spec);
        }
    }
    if include_unknown {
        Some(spec!(
            "unknown",
            LanguageFamily::Fallback,
            &[],
            &[],
            true,
            true,
            true,
        ))
    } else {
        None
    }
}
