//! X06.9 parity/benchmark harness SKELETON entry point: parses all 250
//! QA rows, executes every wired [`feature_parity::runners::RowRunner`]
//! against the fixture corpus, and emits the two required proof
//! artifacts (`proof/memory/x06-rag-qa.json`,
//! `proof/memory/x06-feature-parity.json`) so their honest wired vs
//! unrunnable state is committed and inspectable -- never a fabricated
//! green.
//!
//! Per the mission brief: "parallel lanes are still building tools; a
//! full green run is impossible today and you must NOT fabricate one." This
//! file's own assertions reflect that -- it asserts the row-parse count,
//! the wired-vs-unrunnable split is internally consistent, and the
//! feature-parity rollup correctly refuses to claim
//! `allMatrixPrefixesGreen` today. It does NOT assert every QA row
//! passes.

mod feature_parity;

use feature_parity::proof::{
    build_feature_parity_document, build_qa_proof_document, write_json_document, MatrixPrefixRow,
    PrefixStatus, REQUIRED_PREFIXES,
};
use feature_parity::runners::run_all;
use feature_parity::{build_fixtures, BoxError};
use std::collections::BTreeMap;
use std::path::Path;

type TestResult<T = ()> = Result<T, BoxError>;

/// End-to-end: parse all 250 rows, run them against the fixture
/// environment, and assert the honest split the mission brief requires
/// this harness report (never a fabricated all-green).
#[test]
fn qa_gate_runs_every_row_and_reports_an_honest_wired_vs_unrunnable_split() -> TestResult {
    let rows = feature_parity::queryset::parse_all(&feature_parity::queryset::workspace_root())?;
    assert_eq!(rows.len(), 250);

    let fixtures = build_fixtures()?;
    let results = run_all(&rows, &fixtures);
    assert_eq!(results.len(), 250);

    let wired = results.iter().filter(|r| !r.is_unrunnable()).count();
    let unrunnable = results.iter().filter(|r| r.is_unrunnable()).count();
    assert_eq!(wired + unrunnable, 250);
    // Today's honest floor: X06 now wires real fixture-backed
    // Symbol/CodeGraph/Lessons/MCP/CLI/GitHistory and bounded
    // Architecture/Repository runner paths. Retrieval/Reranking claims
    // are deliberately narrow until a real QA corpus exists. The floor
    // is a progress guard, not a green claim; rows without real code or
    // tool evidence must remain unrunnable rather than be guessed.
    assert!(
        wired >= 35,
        "expected at least 35 honestly wired QA rows after X06 runner expansion, got {wired} wired / {unrunnable} unrunnable"
    );
    assert!(
        unrunnable >= 100,
        "expected non-wired rows to remain honestly unrunnable, got {unrunnable} unrunnable / {wired} wired"
    );

    let document = build_qa_proof_document(&results);
    assert_eq!(document.rows_total, 250);
    assert_eq!(
        document.rows_green + document.rows_failed + document.rows_unrunnable,
        250
    );
    let failed_rows: Vec<String> = results
        .iter()
        .filter(|result| result.verdict == "fail")
        .map(|result| result.id.clone())
        .collect();
    assert_eq!(
        document.rows_failed, 0,
        "fixture-backed default QA runners should either pass or stay unrunnable; failures usually mean an over-broad runner claim: {failed_rows:?}"
    );
    for install_hook_row in ["QA-135", "QA-247"] {
        let Some(result) = results.iter().find(|result| result.id == install_hook_row) else {
            return Err(format!(
                "expected Claude install-hook guard row {install_hook_row} to exist"
            )
            .into());
        };
        assert!(
            result.is_unrunnable(),
            "{install_hook_row} must remain unrunnable until Claude install-hook parity is in scope, got {}",
            result.verdict
        );
    }

    // Emit the proof artifact. Committed per this lane's file claims
    // (`proof/memory/x06-rag-qa.json` ... generated by the tests,
    // committed).
    let workspace_root = feature_parity::queryset::workspace_root();
    let qa_path = workspace_root.join("proof/memory/x06-rag-qa.json");
    write_json_document(&qa_path, &document)?;

    // Build and emit the feature-parity rollup from committed proof
    // artifacts. This is intentionally not an all-green claim: partial
    // proofs become Red with a concrete reason, missing proofs remain
    // Pending, and only artifacts with a real pass signal become Green.
    let mut prefixes =
        current_prefix_statuses(&workspace_root, document.rows_green, document.rows_total)?;
    let qa_status = if document.rows_green == document.rows_total {
        PrefixStatus::Green
    } else {
        PrefixStatus::Red
    };
    prefixes.insert(
        "QA",
        MatrixPrefixRow {
            prefix: "QA".to_string(),
            status: qa_status,
            test_name: Some(
                "qa_gate_runs_every_row_and_reports_an_honest_wired_vs_unrunnable_split"
                    .to_string(),
            ),
            artifact_path: "proof/memory/x06-rag-qa.json".to_string(),
            failure_reason: if matches!(qa_status, PrefixStatus::Red) {
                Some(format!(
                    "{unrunnable} of 250 rows unrunnable, {failed} failed -- see x06-rag-qa.json",
                    failed = document.rows_failed
                ))
            } else {
                None
            },
        },
    );

    let rollup = build_feature_parity_document(&prefixes, &results);
    assert!(
        !rollup.all_matrix_prefixes_green,
        "the rollup must NOT claim all-green while prefixes are Pending/Red -- fabricated green is failure (OWNER_INTENT)"
    );
    assert_eq!(rollup.qa_rows_total, 250);
    assert!(rollup.kg_parity_compared_against_baseline);
    assert!(rollup.local_dense_retrieval_present);
    assert!(rollup.local_reranker_present);
    assert!(rollup.token_reduction_median_at_least_10x);
    assert!(rollup.mcp_cli_parity);
    assert!(rollup.retrieval_improvement_curve_present);

    let rollup_path = workspace_root.join("proof/memory/x06-feature-parity.json");
    write_json_document(&rollup_path, &rollup)?;
    Ok(())
}

/// Map a TEST_MATRIX prefix to the doc-specified artifact filename stem
/// (`MEMORY_RETRIEVAL_TEST_MATRIX.md`'s own table: most prefixes are
/// `x06-<lowercase-area>.json`, but a few use a different area name
/// than their prefix, e.g. `GPH` -> `x06-kg.json`, `COD` ->
/// `x06-code-graph.json`, `PAR` -> `x06-kg-parity.json`).
fn prefix_artifact_stem(prefix: &'static str) -> &'static str {
    match prefix {
        "STO" => "store",
        "IDX" => "indexing",
        "COD" => "code-graph",
        "GPH" => "kg",
        "TXT" => "fulltext",
        "VEC" => "vector",
        "RRK" => "reranker",
        "SUM" => "summaries",
        "WVR" => "weaver",
        "MCP" => "mcp",
        "CLI" => "cli",
        "PAR" => "kg-parity",
        "QA" => "rag-qa",
        "LRN" => "learning-curve",
        "FED" => "federation",
        "DIA" => "diagnostics",
        "SEC" => "policy",
        "TOK" => "token-reduction",
        "MOD" => "models",
        "DOG" => "dogfood",
        // Every entry in REQUIRED_PREFIXES is matched explicitly above;
        // this arm exists only so the match is exhaustive over the
        // input type, never so it can silently invent a stem for an
        // unmapped prefix -- see the coverage test below.
        _ => "unmapped-prefix",
    }
}

fn current_prefix_statuses(
    workspace_root: &Path,
    qa_rows_green: usize,
    qa_rows_total: usize,
) -> TestResult<BTreeMap<&'static str, MatrixPrefixRow>> {
    let mut prefixes: BTreeMap<&'static str, MatrixPrefixRow> = REQUIRED_PREFIXES
        .iter()
        .map(|prefix| (*prefix, pending_prefix(prefix)))
        .collect();

    set_store_status(workspace_root, &mut prefixes)?;
    set_artifact_status(
        workspace_root,
        &mut prefixes,
        "IDX",
        "proof/memory/x06-indexing.json",
        "x06-indexing",
    )?;
    set_artifact_status(
        workspace_root,
        &mut prefixes,
        "COD",
        "proof/memory/x06-code-graph.json",
        "x06-code-graph",
    )?;
    set_rag_status(workspace_root, &mut prefixes)?;
    set_kg_status(workspace_root, &mut prefixes)?;
    set_artifact_status(
        workspace_root,
        &mut prefixes,
        "SUM",
        "proof/memory/x06-summaries.json",
        "x06-summaries",
    )?;
    set_artifact_status(
        workspace_root,
        &mut prefixes,
        "WVR",
        "proof/memory/x06-weaver.json",
        "x06-weaver",
    )?;
    set_artifact_status(
        workspace_root,
        &mut prefixes,
        "MCP",
        "proof/memory/x06-mcp.json",
        "x06-mcp",
    )?;
    set_artifact_status(
        workspace_root,
        &mut prefixes,
        "CLI",
        "proof/memory/x06-cli.json",
        "x06-cli",
    )?;
    set_kg_parity_status(workspace_root, &mut prefixes)?;
    set_learning_status(workspace_root, &mut prefixes)?;
    set_artifact_status(
        workspace_root,
        &mut prefixes,
        "FED",
        "proof/memory/x06-federation.json",
        "x06-federation",
    )?;
    set_artifact_status(
        workspace_root,
        &mut prefixes,
        "DIA",
        "proof/memory/x06-diagnostics.json",
        "x06-diagnostics",
    )?;
    set_artifact_status(
        workspace_root,
        &mut prefixes,
        "SEC",
        "proof/memory/x06-policy.json",
        "x06-policy-filters",
    )?;
    set_token_status(workspace_root, &mut prefixes)?;
    set_model_status(workspace_root, &mut prefixes)?;
    set_dogfood_status(workspace_root, &mut prefixes)?;

    if qa_rows_green == qa_rows_total {
        prefixes.insert(
            "QA",
            green_prefix(
                "QA",
                "proof/memory/x06-rag-qa.json",
                "qa_gate_runs_every_row_and_reports_an_honest_wired_vs_unrunnable_split",
            ),
        );
    }

    Ok(prefixes)
}

fn pending_prefix(prefix: &'static str) -> MatrixPrefixRow {
    MatrixPrefixRow {
        prefix: prefix.to_string(),
        status: PrefixStatus::Pending,
        test_name: None,
        artifact_path: format!("proof/memory/x06-{}.json", prefix_artifact_stem(prefix)),
        failure_reason: Some(
            "proof artifact not emitted or not owned by this X06 slice".to_string(),
        ),
    }
}

fn green_prefix(prefix: &str, artifact_path: &str, test_name: &str) -> MatrixPrefixRow {
    MatrixPrefixRow {
        prefix: prefix.to_string(),
        status: PrefixStatus::Green,
        test_name: Some(test_name.to_string()),
        artifact_path: artifact_path.to_string(),
        failure_reason: None,
    }
}

fn red_prefix(
    prefix: &str,
    artifact_path: &str,
    test_name: Option<&str>,
    failure_reason: impl Into<String>,
) -> MatrixPrefixRow {
    MatrixPrefixRow {
        prefix: prefix.to_string(),
        status: PrefixStatus::Red,
        test_name: test_name.map(str::to_string),
        artifact_path: artifact_path.to_string(),
        failure_reason: Some(failure_reason.into()),
    }
}

fn proof_json(workspace_root: &Path, artifact_path: &str) -> TestResult<Option<serde_json::Value>> {
    let path = workspace_root.join(artifact_path);
    if !path.is_file() {
        return Ok(None);
    }
    let body = std::fs::read_to_string(&path)?;
    Ok(Some(serde_json::from_str(&body)?))
}

fn artifact_status(
    proof: &serde_json::Value,
    prefix: &str,
    artifact_path: &str,
    test_name: &str,
) -> MatrixPrefixRow {
    let status = proof["status"].as_str().unwrap_or("unknown");
    let tests_failed = proof["result"]["testsFailed"].as_u64().unwrap_or(1);
    if (status == "green" || status == "complete") && tests_failed == 0 {
        green_prefix(prefix, artifact_path, test_name)
    } else {
        red_prefix(
            prefix,
            artifact_path,
            Some(test_name),
            format!("artifact status={status}, testsFailed={tests_failed}"),
        )
    }
}

fn set_artifact_status(
    workspace_root: &Path,
    prefixes: &mut BTreeMap<&'static str, MatrixPrefixRow>,
    prefix: &'static str,
    artifact_path: &'static str,
    test_name: &'static str,
) -> TestResult<()> {
    let Some(proof) = proof_json(workspace_root, artifact_path)? else {
        return Ok(());
    };
    prefixes.insert(
        prefix,
        artifact_status(&proof, prefix, artifact_path, test_name),
    );
    Ok(())
}

fn set_store_status(
    workspace_root: &Path,
    prefixes: &mut BTreeMap<&'static str, MatrixPrefixRow>,
) -> TestResult<()> {
    let Some(store) = proof_json(workspace_root, "proof/memory/x06-store.json")? else {
        return Ok(());
    };
    let tests_failed = store["result"]["testsFailed"].as_u64().unwrap_or(1);
    prefixes.insert(
        "STO",
        if tests_failed == 0 {
            green_prefix("STO", "proof/memory/x06-store.json", "memory-store-core")
        } else {
            red_prefix(
                "STO",
                "proof/memory/x06-store.json",
                Some("memory-store-core"),
                format!("store proof reports {tests_failed} failed tests"),
            )
        },
    );
    Ok(())
}

fn set_rag_status(
    workspace_root: &Path,
    prefixes: &mut BTreeMap<&'static str, MatrixPrefixRow>,
) -> TestResult<()> {
    set_artifact_status(
        workspace_root,
        prefixes,
        "TXT",
        "proof/memory/x06-fulltext.json",
        "x06-fulltext",
    )?;
    set_artifact_status(
        workspace_root,
        prefixes,
        "VEC",
        "proof/memory/x06-vector.json",
        "x06-vector",
    )?;
    set_artifact_status(
        workspace_root,
        prefixes,
        "RRK",
        "proof/memory/x06-reranker.json",
        "x06-reranker",
    )?;
    Ok(())
}

fn set_kg_status(
    workspace_root: &Path,
    prefixes: &mut BTreeMap<&'static str, MatrixPrefixRow>,
) -> TestResult<()> {
    let Some(kg) = proof_json(workspace_root, "proof/memory/x06-kg.json")? else {
        return Ok(());
    };
    let status = kg["status"].as_str().unwrap_or("unknown");
    prefixes.insert(
        "GPH",
        if status == "green" || status == "complete" {
            green_prefix("GPH", "proof/memory/x06-kg.json", "x06-kg")
        } else {
            let remaining = kg["remaining"]
                .as_array()
                .map(|items| {
                    items
                        .iter()
                        .filter_map(|item| item.as_str())
                        .filter(|item| !item.contains("Claude parity lane"))
                        .collect::<Vec<_>>()
                        .join("; ")
                })
                .filter(|text| !text.is_empty())
                .unwrap_or_else(|| format!("KG artifact status is {status}"));
            red_prefix("GPH", "proof/memory/x06-kg.json", Some("x06-kg"), remaining)
        },
    );
    Ok(())
}

fn set_kg_parity_status(
    workspace_root: &Path,
    prefixes: &mut BTreeMap<&'static str, MatrixPrefixRow>,
) -> TestResult<()> {
    let Some(parity) = proof_json(workspace_root, "proof/memory/x06-kg-parity.json")? else {
        return Ok(());
    };
    let baseline_executed = parity["baseline_executed"].as_bool().unwrap_or(false);
    let worse = parity["tools_worse"].as_u64().unwrap_or(1);
    let unrunnable = parity["tools_unrunnable"].as_u64().unwrap_or(1);
    prefixes.insert(
        "PAR",
        if baseline_executed && worse == 0 && unrunnable == 0 {
            green_prefix("PAR", "proof/memory/x06-kg-parity.json", "x06-live-baseline-parity")
        } else {
            red_prefix(
                "PAR",
                "proof/memory/x06-kg-parity.json",
                Some("x06-live-baseline-parity"),
                format!(
                    "baseline_executed={baseline_executed}, tools_worse={worse}, tools_unrunnable={unrunnable}"
                ),
            )
        },
    );
    Ok(())
}

fn set_learning_status(
    workspace_root: &Path,
    prefixes: &mut BTreeMap<&'static str, MatrixPrefixRow>,
) -> TestResult<()> {
    let Some(learning) = proof_json(workspace_root, "proof/memory/x06-learning-curve.json")? else {
        return Ok(());
    };
    let present = learning["learningCurve"]["present"]
        .as_bool()
        .unwrap_or(false);
    let blockers = learning["blockers"]
        .as_array()
        .map(|items| {
            items
                .iter()
                .filter_map(|item| item.as_str())
                .collect::<Vec<_>>()
                .join("; ")
        })
        .unwrap_or_default();
    prefixes.insert(
        "LRN",
        if present && blockers.is_empty() {
            green_prefix(
                "LRN",
                "proof/memory/x06-learning-curve.json",
                "x06-learning-curve",
            )
        } else {
            red_prefix(
                "LRN",
                "proof/memory/x06-learning-curve.json",
                Some("x06-learning-curve"),
                if present {
                    format!("store-backed learning present, but follow-up remains: {blockers}")
                } else {
                    "learning curve proof is not present".to_string()
                },
            )
        },
    );
    Ok(())
}

fn set_token_status(
    workspace_root: &Path,
    prefixes: &mut BTreeMap<&'static str, MatrixPrefixRow>,
) -> TestResult<()> {
    let Some(token) = proof_json(workspace_root, "proof/memory/x06-token-reduction.json")? else {
        return Ok(());
    };
    let passes = token["passes10xGate"].as_bool().unwrap_or(false);
    let median = token["medianReductionRatio"].as_f64().unwrap_or_default();
    prefixes.insert(
        "TOK",
        if passes {
            green_prefix(
                "TOK",
                "proof/memory/x06-token-reduction.json",
                "x06-token-reduction",
            )
        } else {
            red_prefix(
                "TOK",
                "proof/memory/x06-token-reduction.json",
                Some("x06-token-reduction"),
                format!("median token reduction ratio {median:.2} does not pass 10x gate"),
            )
        },
    );
    Ok(())
}

fn set_model_status(
    workspace_root: &Path,
    prefixes: &mut BTreeMap<&'static str, MatrixPrefixRow>,
) -> TestResult<()> {
    let chat_ok = proof_json(
        workspace_root,
        "proof/memory/x06-models-qwen3-4b-vulkan-windows-local.json",
    )?
    .and_then(|proof| proof["chatGenerationGguf"]["usability"]["ok"].as_bool());
    let embedding_ok = proof_json(
        workspace_root,
        "proof/memory/x06-models-qwen3-embedding-ort-cpu.json",
    )?
    .and_then(|proof| proof["qwenEmbeddingOnnx"]["ok"].as_bool());
    let reranker_ok = proof_json(
        workspace_root,
        "proof/memory/x06-models-qwen3-reranker-ort-cpu.json",
    )?
    .and_then(|proof| proof["qwenRerankerOnnx"]["ok"].as_bool());
    prefixes.insert(
        "MOD",
        if chat_ok == Some(true) && embedding_ok == Some(true) && reranker_ok == Some(true) {
            green_prefix("MOD", "proof/memory/x06-models.json", "x06-real-model-runtime-proof")
        } else {
            red_prefix(
                "MOD",
                "proof/memory/x06-models.json",
                Some("x06-real-model-runtime-proof"),
                format!(
                    "model proof incomplete: chat_ok={chat_ok:?}, embedding_ok={embedding_ok:?}, reranker_ok={reranker_ok:?}"
                ),
            )
        },
    );
    Ok(())
}

fn set_dogfood_status(
    workspace_root: &Path,
    prefixes: &mut BTreeMap<&'static str, MatrixPrefixRow>,
) -> TestResult<()> {
    let Some(dogfood) = proof_json(workspace_root, "proof/memory/x06-dogfood.json")? else {
        return Ok(());
    };
    let green_gates = dogfood["greenGates"].as_array().map_or(0, Vec::len);
    let lessons = dogfood["lessons"].as_array().map_or(0, Vec::len);
    prefixes.insert(
        "DOG",
        if green_gates > 0 && lessons > 0 {
            green_prefix("DOG", "proof/memory/x06-dogfood.json", "x06-dogfood-closeout")
        } else {
            red_prefix(
                "DOG",
                "proof/memory/x06-dogfood.json",
                Some("x06-dogfood-closeout"),
                format!("dogfood proof missing gates or lessons: green_gates={green_gates}, lessons={lessons}"),
            )
        },
    );
    Ok(())
}

#[test]
fn prefix_artifact_stem_covers_every_required_prefix() {
    for prefix in REQUIRED_PREFIXES {
        let stem = prefix_artifact_stem(prefix);
        assert!(
            stem.chars()
                .all(|character| character.is_ascii_lowercase() || character == '-'),
            "prefix {prefix} mapped to non-artifact-safe stem {stem}"
        );
        assert_ne!(
            stem, "unmapped-prefix",
            "prefix {prefix} fell through to the unmapped default -- add its mapping"
        );
    }
}
