//! X06.9 parity/benchmark harness SKELETON entry point: parses all 250
//! QA rows, executes every wired [`feature_parity::runners::RowRunner`]
//! against the fixture corpus, and emits the two required proof
//! artifacts (`proof/memory/x06-rag-qa.json`,
//! `proof/memory/x06-feature-parity.json`) so their honest wired vs
//! unrunnable state is committed and inspectable -- never a fabricated
//! green.
//!
//! Per the mission brief: "parallel lanes are still building tools; a
//! full green run is impossible today and you must NOT fake one." This
//! file's own assertions reflect that -- it asserts the row-parse count,
//! the wired-vs-unrunnable split is internally consistent, and the
//! feature-parity rollup correctly refuses to claim
//! `allMatrixPrefixesGreen` today. It does NOT assert every QA row
//! passes.

mod feature_parity;

use feature_parity::proof::{
    build_feature_parity_document, build_qa_proof_document, write_json_document, MatrixPrefixRow,
    PrefixStatus, REQUIRED_PREFIXES,
};
use feature_parity::runners::run_all;
use feature_parity::{build_fixtures, BoxError};
use std::collections::BTreeMap;

type TestResult = Result<(), BoxError>;

/// End-to-end: parse all 250 rows, run them against the fixture
/// environment, and assert the honest split the mission brief requires
/// this harness report (never a fabricated all-green).
#[test]
fn qa_gate_runs_every_row_and_reports_an_honest_wired_vs_unrunnable_split() -> TestResult {
    let rows = feature_parity::queryset::parse_all(&feature_parity::queryset::workspace_root())?;
    assert_eq!(rows.len(), 250);

    let fixtures = build_fixtures()?;
    let results = run_all(&rows, &fixtures);
    assert_eq!(results.len(), 250);

    let wired = results.iter().filter(|r| !r.is_unrunnable()).count();
    let unrunnable = results.iter().filter(|r| r.is_unrunnable()).count();
    assert_eq!(wired + unrunnable, 250);
    // Today's honest floor: X06 now wires real fixture-backed
    // Symbol/CodeGraph/Lessons/MCP/CLI/GitHistory and bounded
    // Architecture/Repository runner paths. Retrieval/Reranking claims
    // are deliberately narrow until a real QA corpus exists. The floor
    // is a progress guard, not a green claim; rows without real code or
    // tool evidence must remain unrunnable rather than be guessed.
    assert!(
        wired >= 35,
        "expected at least 35 honestly wired QA rows after X06 runner expansion, got {wired} wired / {unrunnable} unrunnable"
    );
    assert!(
        unrunnable >= 100,
        "expected non-wired rows to remain honestly unrunnable, got {unrunnable} unrunnable / {wired} wired"
    );

    let document = build_qa_proof_document(&results);
    assert_eq!(document.rows_total, 250);
    assert_eq!(
        document.rows_green + document.rows_failed + document.rows_unrunnable,
        250
    );
    assert_eq!(
        document.rows_failed, 0,
        "fixture-backed default QA runners should either pass or stay unrunnable; failures usually mean an over-broad runner claim"
    );
    for install_hook_row in ["QA-135", "QA-247"] {
        let Some(result) = results.iter().find(|result| result.id == install_hook_row) else {
            return Err(format!(
                "expected Claude install-hook guard row {install_hook_row} to exist"
            )
            .into());
        };
        assert!(
            result.is_unrunnable(),
            "{install_hook_row} must remain unrunnable until Claude install-hook parity is in scope, got {}",
            result.verdict
        );
    }

    // Emit the proof artifact. Committed per this lane's file claims
    // (`proof/memory/x06-rag-qa.json` ... generated by the tests,
    // committed).
    let workspace_root = feature_parity::queryset::workspace_root();
    let qa_path = workspace_root.join("proof/memory/x06-rag-qa.json");
    write_json_document(&qa_path, &document)?;

    // Build and emit the feature-parity rollup. Every non-QA prefix is
    // conservatively Pending here unless a dedicated subpack proof has
    // promoted it elsewhere. QA is Red (not Green) until all rows are
    // runnable and passing.
    let qa_status = if document.rows_green == document.rows_total {
        PrefixStatus::Green
    } else {
        PrefixStatus::Red
    };
    let mut prefixes: BTreeMap<&'static str, MatrixPrefixRow> = REQUIRED_PREFIXES
        .iter()
        .map(|prefix| {
            (
                *prefix,
                MatrixPrefixRow {
                    prefix: prefix.to_string(),
                    status: PrefixStatus::Pending,
                    test_name: None,
                    artifact_path: format!(
                        "proof/memory/x06-{}.json",
                        prefix_artifact_stem(prefix)
                    ),
                    failure_reason: Some(
                        "not yet emitted by its owning X06 subpack as of the X06.9 skeleton pass"
                            .to_string(),
                    ),
                },
            )
        })
        .collect();
    prefixes.insert(
        "QA",
        MatrixPrefixRow {
            prefix: "QA".to_string(),
            status: qa_status,
            test_name: Some(
                "qa_gate_runs_every_row_and_reports_an_honest_wired_vs_unrunnable_split"
                    .to_string(),
            ),
            artifact_path: "proof/memory/x06-rag-qa.json".to_string(),
            failure_reason: if matches!(qa_status, PrefixStatus::Red) {
                Some(format!(
                    "{unrunnable} of 250 rows unrunnable, {failed} failed -- see x06-rag-qa.json",
                    failed = document.rows_failed
                ))
            } else {
                None
            },
        },
    );

    let rollup = build_feature_parity_document(&prefixes, &results);
    assert!(
        !rollup.all_matrix_prefixes_green,
        "the rollup must NOT claim all-green while prefixes are Pending and QA is Red -- fake green is failure (OWNER_INTENT)"
    );
    assert_eq!(rollup.qa_rows_total, 250);

    let rollup_path = workspace_root.join("proof/memory/x06-feature-parity.json");
    write_json_document(&rollup_path, &rollup)?;
    Ok(())
}

/// Map a TEST_MATRIX prefix to the doc-specified artifact filename stem
/// (`MEMORY_RETRIEVAL_TEST_MATRIX.md`'s own table: most prefixes are
/// `x06-<lowercase-area>.json`, but a few use a different area name
/// than their prefix, e.g. `GPH` -> `x06-kg.json`, `COD` ->
/// `x06-code-graph.json`, `PAR` -> `x06-kg-parity.json`).
fn prefix_artifact_stem(prefix: &'static str) -> &'static str {
    match prefix {
        "STO" => "store",
        "IDX" => "indexing",
        "COD" => "code-graph",
        "GPH" => "kg",
        "TXT" => "fulltext",
        "VEC" => "vector",
        "RRK" => "reranker",
        "SUM" => "summaries",
        "WVR" => "weaver",
        "MCP" => "mcp",
        "CLI" => "cli",
        "PAR" => "kg-parity",
        "QA" => "rag-qa",
        "LRN" => "learning-curve",
        "FED" => "federation",
        "DIA" => "diagnostics",
        "SEC" => "policy",
        "TOK" => "token-reduction",
        "MOD" => "models",
        "DOG" => "dogfood",
        // Every entry in REQUIRED_PREFIXES is matched explicitly above;
        // this arm exists only so the match is exhaustive over the
        // input type, never so it can silently invent a stem for an
        // unmapped prefix -- see the coverage test below.
        _ => "unmapped-prefix",
    }
}

#[test]
fn prefix_artifact_stem_covers_every_required_prefix() {
    for prefix in REQUIRED_PREFIXES {
        let stem = prefix_artifact_stem(prefix);
        assert!(!stem.is_empty());
        assert_ne!(
            stem, "unmapped-prefix",
            "prefix {prefix} fell through to the unmapped default -- add its mapping"
        );
    }
}
