//! Black-box proof that the native CLI preserves the frozen generated-source marker gate.

use std::process::Command;

#[test]
fn generated_artifacts_policy_rejects_a_frozen_gen_1_1_marker() -> Result<(), std::io::Error> {
    let temp = tempfile::tempdir()?;
    std::fs::create_dir_all(temp.path().join("src"))?;
    std::fs::write(
        temp.path().join("ocentra-enforcer.config.json"),
        r#"{"schemaVersion":2,"profileName":"default"}"#,
    )?;
    std::fs::write(
        temp.path().join("src/generated.rs"),
        "// <auto-generated>\npub const VALUE: u8 = 1;\n",
    )?;
    let output = Command::new(env!("CARGO_BIN_EXE_enforcer"))
        .args(["policy", "generated-artifacts"])
        .current_dir(temp.path())
        .output()?;
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert_eq!(output.status.code(), Some(1), "stdout: {stdout}");
    assert!(stdout.contains("GEN-1.1"), "stdout: {stdout}");
    Ok(())
}
