// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source line attached to a finding, including aggregate findings that have
 * no single source line.
 *Canonical domain representation for FindingLine.
 */
export type FindingLine = number;
