// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FindingDetail } from "./FindingDetail";
import type { FindingLine } from "./FindingLine";
import type { FindingSnippet } from "./FindingSnippet";
import type { FindingTitle } from "./FindingTitle";
import type { RelPath } from "./RelPath";
import type { RuleId } from "./RuleId";
import type { Severity } from "./Severity";

/**
 * One finding produced by a rule against a file location.
 *Canonical domain representation for Finding.
 */
export type Finding = {
/**
 * Rule that fired.
 */
ruleId: RuleId,
/**
 * Severity of this occurrence.
 */
severity: Severity,
/**
 * Short human title of the rule.
 */
title: FindingTitle,
/**
 * Occurrence-specific detail.
 */
detail: FindingDetail,
/**
 * Repo-relative file the finding points at.
 */
file: RelPath,
/**
 * 1-based line number.
 */
line: FindingLine,
/**
 * Optional offending source excerpt (already redacted upstream).
 */
snippet: FindingSnippet | null, };
