// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelPath } from "./RelPath";
import type { RuleId } from "./RuleId";
import type { Severity } from "./Severity";

/**
 * One finding produced by a rule against a file location.
 */
export type Finding = { 
/**
 * Rule that fired.
 */
ruleId: RuleId, 
/**
 * Severity of this occurrence.
 */
severity: Severity, 
/**
 * Short human title of the rule.
 */
title: string, 
/**
 * Occurrence-specific detail.
 */
detail: string, 
/**
 * Repo-relative file the finding points at.
 */
file: RelPath, 
/**
 * 1-based line number.
 */
line: number, 
/**
 * Optional offending source excerpt (already redacted upstream).
 */
snippet: string | null, };
