// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a report contains no blocking violations.
 *Canonical domain representation for ReportOutcome.
 */
export type ReportOutcome = boolean;
