// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { ReportOutcome } from "./ReportOutcome";
import type { ScanScope } from "./ScanScope";
import type { Violation } from "./Violation";

/**
 * The report a check/scan run returns to callers (CLI, MCP, CI).
 *Canonical domain representation for Report.
 */
export type Report = {
/**
 * True when no blocking violations were found.
 */
ok: ReportOutcome,
/**
 * What the run covered.
 */
scope: ScanScope,
/**
 * Blocking violations.
 */
violations: Array<Violation>,
/**
 * Non-blocking warnings.
 */
warnings: Array<Finding>,
/**
 * Findings suppressed by an explicit waiver.
 */
waived: Array<Finding>,
/**
 * Every finding (violations + warnings + waived, denormalized for
 * consumers that want one list).
 */
findings: Array<Finding>, };
