// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Branded rule identifier (e.g. `RR-6.1`, `DEP-1.1`).
 */
export type RuleId = string;
