// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a validation run covered.
 *Canonical domain representation for ScanScope.
 */
export type ScanScope = "Workspace" | "Files" | "Crate" | "Diff";
