// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Finding severity, lowercase on the wire (`"error"`, `"warning"`,
 * `"info"`) to match the legacy `.mjs` report shape.
 *The closed severity classification emitted with a finding.
 */
export type Severity = string;
