// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The UI's rendering of one [`Finding`]/[`Violation`] row: the exact
 * shape the report-view/actions frontend needs (ruleId + severity +
 * title/detail + file:line + an optional excerpt), denormalized so the
 * frontend never has to re-derive display fields from the raw domain
 * type.
 */
export type UiFindingRowResponse = {
/**
 * Rule that fired, as its wire string (e.g. `"RR-6.1"`).
 */
ruleId: string,
/**
 * Severity, lowercase wire form (`"error"`/`"warning"`).
 */
severity: string,
/**
 * Short human title of the rule.
 */
title: string,
/**
 * Occurrence-specific detail.
 */
detail: string,
/**
 * Repo-relative file the finding points at.
 */
file: string,
/**
 * 1-based line number.
 */
line: number,
/**
 * Optional offending source excerpt (already redacted upstream).
 */
snippet: string | null, };
