// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiFindingRow } from "./UiFindingRow";

/**
 * The UI's rendering of a whole [`Report`]: the payload the served-HTML
 * fallback and the Tauri report view both consume. `ok`/counts are
 * denormalized alongside the row lists so the frontend never counts
 * rows itself (single source of truth for the summary line).
 */
export type UiReportPayload = { 
/**
 * True when no blocking violations were found.
 */
ok: boolean, 
/**
 * What the run covered, as its wire string (e.g. `"workspace"`).
 */
scope: string, 
/**
 * Blocking violation rows.
 */
violations: Array<UiFindingRow>, 
/**
 * Non-blocking warning rows.
 */
warnings: Array<UiFindingRow>, 
/**
 * Rows suppressed by an explicit named waiver.
 */
waived: Array<UiFindingRow>, 
/**
 * Total finding count across violations + warnings + waived
 * (denormalized so the frontend never has to sum three arrays for
 * the summary line).
 */
totalCount: number, };
