// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";

/**
 * A BLOCKING finding. Invariant: severity is [`Severity::Error`], enforced
 * at construction — a non-error finding cannot become a `Violation`.
 */
export type Violation = Finding;
